spring.application.name=demoservice

#-------------TOKEN GENERATION----------------
#Token generation request id
token.request.id=io.mosip.registration.processor
#Token generation app id
token.request.appid=regproc
#Token generation username
token.request.username=registrationprocessor
#Token generation password
token.request.password=abc123
#Token generation version
token.request.version=1.0
#Token generation Client Id
token.request.clientId=mosip-regproc-client
#Token generation secret key
token.request.secretKey=9T92VHe7RKujy5Cq
#Token generation issuer url
token.request.issuerUrl=https://iam.lesotho.mosip.net/auth/realms/mosip

mosip.auth.adapter.impl.basepackage=io.mosip.kernel.auth.defaultadapter

mosip.iam.adapter.clientid=mobile-verifier
mosip.iam.adapter.clientsecret=GYcISodCZMI9PR4QqpKTzyuGhOJyBxQO
mosip.iam.adapter.appid=admin


verify.api.url=https://dev.verification.custom-it.co.ls/verify/citizen
verify.api.key=d8f3cb5ef9b2311eacd17311b3bcbb4bc525f220a2b30f73776e338cec683632